language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database zab_ui_test;' -U postgres
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: gevlk5BjCiUB1Yzv/aNhWjcR0cDTmFfnFE7hmyu9IM2y5wI65WGSgYcy9aoNYZkma8acdP49KN7dwf8Rr1rC/V3vwdFXrMmF0DdL8yiGA2VqnsupZDvzWJcgXoZ+WQWInjmuV6g039j3ld5sF1DQbePj+o/ALfxzcGkBpIRxVkRggxxIfiFQ/cPT2P+tLF9ehI7bTvHsEWMbxGzjZ8wxbXZbbR+OkW0YuL8REA0tETzEinihNcbksFDrdCIGxulVrjwHyEYgP+abOdL2SFLNT3Mixf6A2QM6kpV1dlj8SCQeuslircUH7+GQNXp7vpIePOStPldecHnHjI7dnCV7upH3gYhVL570WYEmDgrEcAxb674qGQMf16RX9XmhPqQLvylVJYPalGH/3XMWCrkjEVJYpbh5+KfrYK7/4+cxCn1dpcSFySh2rB1GflCsnUPxdxGPJH86MkEzLykpgwb20hLFCBkQte/0FamdBNtWhEik7hgJah0Di+lD1p8kMl0l5CmN1fq57f6JLULqkOhmRVk2iF6PBSNL+Z9o1wS2rGs0K94pkQamLN44Jbo0qwXNvKPS4PFgDhrfntvCsn29PU2Av/AinDxuw8ZeRaAe2Y5VFQx+Pfqe+q6+9EQJt+QnCtFprm/Z8tdPNIP1VmAvQVLyZwLmSYkB2MfbHne0on0=
  app: zeroandbeyond
  on:
    repo: hillstew/zab-ui
env:
  global:
    secure: jvFEdoSZ6iIzrlWYhk5gxF2LbiMYrkQxOdgQAGNLWAjjTuqFj5i5hKzq7iVHQnTSjA4Kn089iKjErjawHdw38us2fZWhsNOkXU8Slg+DTCzFfZ1EAvRFmgVCTIp0Gzm3T1dCmRpQbfa5aOyiRghI6f3vS32G3U4/VYRqbzyMkX3DzLh8u+tj0hdvyUj+C4ncvltlesBlfppC7edB1x38XMXkWKtAH9aD0XrAwDZtZ84eGErWIwLHJcmOCxU7iw+VEqovth15DDbwsf0+JxPGPhFTKcKE1odMl3kiVQiiSHSpw56PUiiWMczv77/1hQYLCw3LPH3f9bau9Pc+YnZQL625JhsMpdDf88O4EmD/a5ZEwhYqFOcF3aaaxNnleel7ysdKdRASe1WiguasY9v3PxbApffUXPBJSWREmSo4HAWNfY8QupjkCAn7RN3fYU9bgEktxIKNxklDKL74PRzoS+LwpxjVSBnZIwY+8sNp/crwS0TyuegTpgBK0KYB/ORsgm6kQ9yaJg1JyFhXTZ5FrY9oGIO5X4Svm65bSN9EbpRwInBL4PTbkPs2d4VyDOk8V2dlJ3oBbgBlOIZi3A6PL5BS477gOh7Cf0F6KImIHIawXqfUv8hMzvTEkr+F9lpwUID33w0/8NrEWssXHrrA9GTCDqYXf/ggto1UdCUf5No=
