language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
before_script:
  - psql -c 'create database zab_ui_test;' -U postgres
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: lUIuDVxGzkgAYOzdzbJlHdFr8utUn5lA2A4/a1XNCL5gpwNsvLQfKg3Q6DjEj9Lzez6AMGSn9MRrd8JAAanatkYtEwer6kzv3yJgGgcVbU6RIm99YsJ7rPGzSoFPt7f6KdyIUlrCPtqxZscsTzTQOGhNL3CPB/JaB9SSoeXj9pEhacM4OJv0mioL7/dYrPNGURbFsbl4P5byH8WtYYGybh+7Rr7yLlMqE6vFBCos4mwICdw3WLHkGy8Q/oH1wZtXRLr4ZqB851o7roSd9/DPg4k7E/FG0b2CLzD2iPETkOyxf7T2y9KZcTkmrJLwT5WuAWm4rb88v/e/1aU/lWUEaz+UnxCSjDcqPW4L4KI/I/YdQVkDEAAC2e1eqqVKR5VBVxMw26xOfhznsLwg1EqW9qpv3FnhAp9poV30u7rcrv0T+31TOLxCpNSQbPF39ZXOtNv7h2BFGWKqcdWzcGj6+RJQBySQ/0DlIEaJnY41SWCFRWIG5V8PP8LV29ugcJNYnkHJ5STtFtldo6Ie5yFn8jyNRVBaVkiMt5CyrNtGnfLdAU/t3mNMiA6B9GVPZrukFWbE7XaQkd37BXZq48tcavMrlBdDt/JvGHCA9x1y9KBCfQnRq6dYa1HGEGp5NkjNSIu62vI27rqHXhyXnKiLWrFh4LKYD3lVJseDAJBneO0=
  on:
    repo: hillstew/zab-ui
