language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database zab_ui_test;' -U postgres
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: gevlk5BjCiUB1Yzv/aNhWjcR0cDTmFfnFE7hmyu9IM2y5wI65WGSgYcy9aoNYZkma8acdP49KN7dwf8Rr1rC/V3vwdFXrMmF0DdL8yiGA2VqnsupZDvzWJcgXoZ+WQWInjmuV6g039j3ld5sF1DQbePj+o/ALfxzcGkBpIRxVkRggxxIfiFQ/cPT2P+tLF9ehI7bTvHsEWMbxGzjZ8wxbXZbbR+OkW0YuL8REA0tETzEinihNcbksFDrdCIGxulVrjwHyEYgP+abOdL2SFLNT3Mixf6A2QM6kpV1dlj8SCQeuslircUH7+GQNXp7vpIePOStPldecHnHjI7dnCV7upH3gYhVL570WYEmDgrEcAxb674qGQMf16RX9XmhPqQLvylVJYPalGH/3XMWCrkjEVJYpbh5+KfrYK7/4+cxCn1dpcSFySh2rB1GflCsnUPxdxGPJH86MkEzLykpgwb20hLFCBkQte/0FamdBNtWhEik7hgJah0Di+lD1p8kMl0l5CmN1fq57f6JLULqkOhmRVk2iF6PBSNL+Z9o1wS2rGs0K94pkQamLN44Jbo0qwXNvKPS4PFgDhrfntvCsn29PU2Av/AinDxuw8ZeRaAe2Y5VFQx+Pfqe+q6+9EQJt+QnCtFprm/Z8tdPNIP1VmAvQVLyZwLmSYkB2MfbHne0on0=
  app: zeroandbeyond
  on:
    repo: hillstew/zab-ui
